## Codes to replicate 3D graphs in appendix

library("plot3D")

data1 <- read.csv("imp50_34v.csv",header=TRUE) # for Figure A.9
## Other plots given in the Appendix can be generated by loading other .csv files
# saved  using TVPcodes.R. They are imp50_14.csv (For Figure A.7) and imp50_24v.csv(For Figure A.8)
# Similar fashion Figures A.10, A.11 and A.12 can be generated using draws from Model 2
datalab <- read.csv("datalab.csv",header=TRUE) # timeperiod
YC <- data1
Z <- as.matrix(data1[,-1])
z=t(Z)
#x.axis=1:ncol(z)#t
#y.axis=1:nrow(z)#t
y.axis=1:ncol(z)
x.axis=1:nrow(z)
min.x <- min(x.axis)
max.x <- max(x.axis)

min.y <- min(y.axis)
max.y <- max(y.axis)

min.z <- round(min(z),2)
max.z <- round(max(z),2)
tlabel <- datalab[-(1:42),]

y.axis1 <- seq(1,ncol(z),by=24)#t
#y.axis1 <- seq(1,ncol(z),by=4)
x.axis1 <- seq(1,nrow(z),by=4)#t
#x.axis1 <- seq(1,nrow(z),by=24)
z.axis <- seq(min.z,max.z,by=0.001)
z.axis1 <- seq(min.z,max.z,by=0.1)

pmat <- persp3D (x =x.axis, 
       y = y.axis, z, 
                 phi = 40, theta = 30,
       col="white" , alpha=0.1,border="gray20",      
    
      inttype = 1, curtain = FALSE, add = FALSE, plot = TRUE,
                 ticktype = "detailed",xlab="Time",
                box=FALSE, axes=FALSE)

image3D(x = x.axis, 
      y = y.axis, z = 0, col="black", add = TRUE,alpha = 0.1)
 #Drawing the Axes
lines(trans3d(x.axis, min.y, min.z, pmat) , col="black")
lines(trans3d(max.x, y.axis, min.z, pmat) , col="black")
lines(trans3d(min.x, min.y, z.axis, pmat) , col="black")

#Drawing Tick Marks and labels of z axis
tick.start <- trans3d(min.x, min.y, z.axis1, pmat)
tick.end <- trans3d(min.x, (min.y - 2), z.axis1, pmat)
segments(tick.start$x, tick.start$y, tick.end$x, tick.end$y)

labels <- as.character(z.axis1)
label.pos <- trans3d(min.x, (min.y - 3), z.axis1, pmat)
text(label.pos$x, label.pos$y, labels=labels, adj=c(1, NA), cex=1)
#Drawing Tick Marks and labels of z axis
tick.start <- trans3d(max.x, y.axis1, min.z, pmat)
tick.end <- trans3d(max.x + .5, y.axis1, min.z, pmat)
segments(tick.start$x, tick.start$y, tick.end$x, tick.end$y)

labels <- tlabel[y.axis1]
label.pos <- trans3d((max.x + 1), y.axis1, min.z, pmat)
text(label.pos$x, label.pos$y, labels=labels, adj=c(0, NA), cex=1)
#Drawing Tick Marks and labels 
tick.start <- trans3d(x.axis1, min.y, min.z, pmat)
tick.end <- trans3d(x.axis1, (min.y - 3), min.z, pmat)
segments(tick.start$x, tick.start$y, tick.end$x, tick.end$y)

labels <- as.character(x.axis1)
label.pos <- trans3d(x.axis1, (min.y - 10), min.z, pmat)
text(label.pos$x, label.pos$y, labels=labels, adj=c(0, NA),  cex=1)
